"""Default configuration values for graph-unified."""

from typing import List

# LLM Defaults
DEFAULT_LLM_PROVIDER = "anthropic"
DEFAULT_LLM_MODEL = "claude-3-5-sonnet-20241022"
DEFAULT_LLM_TEMPERATURE = 0.0
DEFAULT_LLM_MAX_TOKENS = 4096
DEFAULT_LLM_TIMEOUT = 60
DEFAULT_LLM_RPM = 50
DEFAULT_LLM_TPM = 40000
DEFAULT_RETRY_MAX_ATTEMPTS = 3
DEFAULT_RETRY_BACKOFF = 2.0

# Embedding Defaults
DEFAULT_EMBEDDING_PROVIDER = "voyage"
DEFAULT_EMBEDDING_MODEL = "voyage-3"
DEFAULT_EMBEDDING_DIMENSION = 1024
DEFAULT_EMBEDDING_BATCH_SIZE = 128
DEFAULT_EMBEDDING_NORMALIZE = True

# Chunking Defaults
DEFAULT_CHUNKING_STRATEGY = "fixed"
DEFAULT_CHUNK_SIZE = 512
DEFAULT_CHUNK_OVERLAP = 64
DEFAULT_RESPECT_BOUNDARIES = True
DEFAULT_ENCODING_NAME = "cl100k_base"

# Extraction Defaults
DEFAULT_ENTITY_TYPES: List[str] = [
    "PERSON",
    "ORGANIZATION",
    "LOCATION",
    "EVENT",
    "CONCEPT",
    "TECHNOLOGY",
]

DEFAULT_RELATIONSHIP_TYPES: List[str] = [
    "RELATED_TO",
    "PART_OF",
    "LOCATED_IN",
    "WORKS_FOR",
    "CAUSES",
]

DEFAULT_MAX_GLEANINGS = 1
DEFAULT_MIN_CONFIDENCE = 0.7
DEFAULT_ENABLE_COREFERENCE = False

# Indexing Defaults
DEFAULT_INDEXING_CHUNK_SIZE = 512
DEFAULT_INDEXING_CHUNK_OVERLAP = 128
DEFAULT_INDEXING_EXTRACTION_BATCH_SIZE = 10
DEFAULT_INDEXING_DEDUP_THRESHOLD = 90
DEFAULT_INDEXING_MAX_CONCURRENT = 10

# Strategies Defaults
DEFAULT_HYBRID_ALPHA = 0.5
DEFAULT_BM25_K1 = 1.5
DEFAULT_BM25_B = 0.75
DEFAULT_LEIDEN_RESOLUTION = 1.0
DEFAULT_MAX_COMMUNITY_SIZE = 50
DEFAULT_GENERATE_REPORTS = True
DEFAULT_LIGHTRAG_ENTITY_WEIGHT = 0.6
DEFAULT_HIPPORAG_PPR_ALPHA = 0.85

# Storage Defaults
DEFAULT_STORAGE_ROOT = "./output"
DEFAULT_PARQUET_COMPRESSION = "snappy"
DEFAULT_VECTOR_DB_BACKEND = "lancedb"
DEFAULT_VECTOR_INDEX_TYPE = "IVF_FLAT"
DEFAULT_CHUNK_INDEX_NAME = "chunks"
DEFAULT_ENTITY_INDEX_NAME = "entities"
DEFAULT_RELATIONSHIP_INDEX_NAME = "relationships"
DEFAULT_FACT_INDEX_NAME = "facts"
DEFAULT_COMMUNITY_INDEX_NAME = "communities"
DEFAULT_GRAPH_FORMAT = "graphml"

# Query Defaults
DEFAULT_QUERY_STRATEGY = "auto"
DEFAULT_TOP_K = 10
DEFAULT_GENERATION_ENABLED = True
DEFAULT_GENERATION_TEMPERATURE = 0.3
DEFAULT_GENERATION_MAX_TOKENS = 1000
DEFAULT_ROUTING_ENABLED = True
DEFAULT_ROUTING_STRATEGY = "rule_based"

# Performance Defaults
DEFAULT_WORKERS = 10
DEFAULT_BATCH_SIZE = 10
DEFAULT_CACHE_EMBEDDINGS = True
DEFAULT_ENABLE_PROFILING = False

# Logging Defaults
DEFAULT_LOG_LEVEL = "INFO"
DEFAULT_LOG_FORMAT = "text"
DEFAULT_LOG_OUTPUT = "stdout"
DEFAULT_LOG_FILE_PATH = "./logs/graphunified.log"
